RadditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :subs
  resource :session
  resources :posts
end

RadditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RadditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord

  validates :title, presence: true
  belongs_to :sub 
  belongs_to :author,
    primary_key: :id, 
    foreign_key: :user_id,
    class_name: :User

end

RadditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post_id, :sub_id, presence: true

  has_many :posts 
  has_many :subs

end

RadditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true 

  belongs_to :moderator, 
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User 
  
  has_many :posts
  


end

RadditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, presence:true, uniqueness:true 
  validates :password_digest, presence:true 
  validates :password, length: {minimum:6, allow_nil:true}
  after_initialize :ensure_session_token!
  attr_accessor :password 

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts

  def password=(password)
    @password=password
    self.password_digest=BCrypt::Password.create(password)
   
  end 

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end  

  def ensure_session_token! 
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token! 
    self.session_token=SecureRandom::urlsafe_base64
    self.save 
    self.session_token 
  end 

  def self.find_by_credentials(username,password)
    user=User.find_by(username: username)
    if user && user.is_password?(password)
      user 
    else  
      nil 
    end 
  end 
end

RadditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def log_in!(user)
    user.reset_session_token!
  end 

  def log_out!(user)
    user.reset_session_token! 
    session[:session_token]=nil
  end  

  def log_in? 
    !!current_user
  end  

  def current_user 
    @current_user||=User.find_by_session_token(session[:session_token])
  end   

  def require_sign_in! 
    redirect_to new_session_url unless sign_in?
  end  
end

RadditClone/app/controllers/post_subs_controller.rb
class PostSubsController < ApplicationController
end

RadditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new 
    @post=Post.new
  end  

  def create 
    @post=Post.new(post_params)
    @post.user_id=current_user.id 
    # @post.sub_id=params[:sub_id]  
    if @post.save 
      redirect_to posts_url
    else
      flash[:errors]=@post.errors.full_messages
      render :new
    end
  end

  def show 
    @post=Post.find(params[:id])
  end  
  
  def edit 
    @post=Post.find(params[:id])
  end  
  
  def update 
    @post=current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else  
      flash[:errors]=@post.errors.full_messages
      render :edit
    end 
  end   

  def destroy 
    @post = Post.find(params[:id])
    @post.destroy 
    redirect_to post_url(@post)
  end   

  def post_params 
    params.require(:post).permit(:title,:url,:content,:sub_id)

end


# sub --> show

# <input type="hidden" name="post[sub_id]" value="<%=@sub.id%>">

RadditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new 
  end  

  def create 
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Invalid Credentials!"]
      render :new
    end
  end 

  def destroy
    @user = User.find(params[:id])
    @user.reset_session_token!
    redirect_to new_session_url
  end

end

RadditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_sign_in! 

  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(param[:id])
  end

  def index 
    @subs = Sub.all
  end

  def create 
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show 
    @sub = Sub.find(param[:id])
  end

  def udpate 
    @sub = current_user.subs.find(params[:id])
    if @sub.udpate_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end 

end

RadditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
  end  

  def create 
    @user=User.new(user_params)
    if @user.save 
      log_in!(@user)
      redirect_to users_url 
    else  
      flash[:errors] = @user.errors.full_messages
      render :new 
    end  
  end  

  def user_params 
    params.require(:user).permit(:username,:password)
  end  
end

RadditClone/app/helpers/application_helper.rb
module ApplicationHelper
  
end

RadditClone/app/helpers/post_subs_helper.rb
module PostSubsHelper
end

RadditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RadditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RadditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RadditClone/app/helpers/users_helper.rb
module UsersHelper
end

RadditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RadditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RadditClone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%=subs_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="_method" value="post">
  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label>
    URL
    <input type="text" name="sub[url]" value="">
  </label>

  <label>
    Content
    <input type="text" name="sub[content]" value="">
  </label>

  <input type="submit" value="Create New Sub">

</form>

RadditClone/app/views/subs/show.html.erb
<%= @sub.title %>
<%= @sub.url %>
<%= current_user.username %>
<h1><%=@sub.title %></h1>
<h2>Description</h2>
<h3><%=@sub.description %></h3>
<a href="<%=new_post_url%>"> Make New Post!</a>


<ul>
  <% @sub.posts.each do |post| %> 
    <li>  
      <a href="<%=post_url(post)%>"><%=post.title%></a>
    </li>
  <% end  %>
    
</ul>
<!-- ???? -->

RadditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url%>" method="post">
  <input type="hidden" name="_method" value="post"> 
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label> 
    Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">

</form>